version: "3"

services:
  ghost:
    image: ghost:5.9.4
    container_name: ghost
    volumes:
      - ./..:/var/lib/ghost/content/themes/liebling:Z
      - ./ghost.db:/var/lib/ghost/content/data/ghost.db:Z
      - ./../images:/var/lib/ghost/content/images
    environment:
      - NODE_ENV=development
    ports:
      - 2368:2368
